echo Downloading Godot...
curl -o godot.zip -L 'https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip'
echo Installing unzip...
sudo apt install unzip
echo Unzipping Godot...
unzip -p godot.zip Godot_v*-stable_linux.x86_64 > godot.x86_64
chmod +xr godot.x86_64
echo Exporting project...
./godot.x86_64 --export-release Web ../WebApp/exported-game/index.html --path ../Game --headless
echo Godot project exported.
